# Enable Num Lock
# pre-requisite: pkg install numlockx
numlockx on

# Plasma
#exec dbus-launch --exit-with-x11 ck-launch-session startplasma-x11

# XFCE
. /usr/local/etc/xdg/xfce4/xinitrc

# Disable screen blanking AFTER XFCE starts
xset s off
xset -dpms
xset s noblank
# Re-enable numlock (XFCE might have disabled it)
numlockx on
