notify 100 {
    match "system" "USB";
    match "subsystem" "DEVICE";
    match "type" "ATTACH";
    match "vendor" "0x04e8";    # Samsung vendor ID
    action "chown <username>:fuse /dev/$cdev && chmod 0660 /dev/$cdev";
};
